[package]
name = "zenoh-backend-timescale-community"
version = "1.6.2"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
dynamic_plugin = []
default = ["dynamic_plugin"]

[dependencies]
git-version = "0.3.5"
async-trait = "0.1.66"
zenoh = { version = "1.6.2", features = [
    "unstable",
    "internal",
    "plugins"
] , git = "https://github.com/eclipse-zenoh/zenoh.git" , branch = "main" }
zenoh_backend_traits = { version = "1.6.2", git = "https://github.com/eclipse-zenoh/zenoh.git" , branch = "main" }
zenoh-plugin-trait = { version = "1.6.2", git = "https://github.com/eclipse-zenoh/zenoh.git" , branch = "main" }
zenoh-util = { version = "1.6.2", git = "https://github.com/eclipse-zenoh/zenoh.git" , branch = "main" }
tokio-postgres = "0.7.15"
tokio = { version = "1.48.0", features = ["full"] }
log = "0.4.28"
postgres-native-tls = "0.5.2"
anyhow = "1.0.100"

[build-dependencies]
rustc_version = "0.4.0"
